Added the ability to specify hpfeeds host and port.

diff --git a/uwsgi.run.j2 b/uwsgi.run.j2
--- a/uwsgi.run.j2
+++ b/uwsgi.run.j2
@@ -117,6 +117,21 @@ then
     MONGODB_PORT="--mongo_port ${MONGODB_PORT}"
   fi
 
+  if [[ ! -z "${HPFEEDS_HOST}" ]]
+  then
+    HPFEEDS_HOST="--hpfeeds_host ${HPFEEDS_HOST}"
+  else
+    HPFEEDS_HOST=""
+  fi
+
+  if [[ -z ${HPFEEDS_PORT} ]]
+  then
+    echo "HPFeeds port is required"
+    exit 1
+  else
+    HPFEEDS_PORT="--hpfeeds_port ${HPFEEDS_PORT}"
+  fi
+
   python generateconfig.py unattended ${EMAIL} \
                                       ${SERVER_BASE_URL} \
                                       ${HONEYMAP_URL} \
@@ -130,9 +145,11 @@ then
                                       ${DEFAULT_MAIL_SENDER} \
                                       ${LOG_FILE_PATH} \
                                       ${MONGODB_HOST} \
-                                      ${MONGODB_PORT}
+                                      ${MONGODB_PORT} \
+                                      ${HPFEEDS_HOST} \
+                                      ${HPFEEDS_PORT}
 
-  python initdatabase.py
+  python initdatabase.py &
 fi
 
 LOG_FILE_PATH=$(awk '/LOG_FILE_PATH/ {print $3}' /opt/config.py |sed "s/'//g")
